Merges security into
hoptond/portfolio pull request #8
Opened 2018-10-04 16:09 UTC by hoptond

Unit tested, dockblocked, minimum viable product. Not much code to look through, one unit test.

Code is login.php,logout.php,security_functions.php

2018-10-04 16:22 UTC, robertkieronreeves commented
Couldn't find any problems.

2018-10-04 16:33 UTC, mporam requested changes

2018-10-04 16:33 UTC, mporam commented on edit/login.php
> +if (verifyLogin($_POST['username'], $_POST['password'])) {
what if username or password keys dont exist?

2018-10-04 16:33 UTC, mporam commented on edit/login.php
> +    setcookie('id', session_id());
you dont need to do this, session_start() does it for you

2018-10-04 16:33 UTC, mporam commented on edit/logout.php
> +setcookie('id',0, time() - 1);
use `session_destroy()` instead, and dont do any cookie stuff

2018-10-04 16:33 UTC, mporam commented on edit/security_functions.php
> +    if ($_COOKIE['id'] != session_id()) {
this is not needed, just check a key in the session

2018-10-04 16:33 UTC, mporam commented on edit/security_functions.php
> +    if ($_COOKIE['id'] != session_id()) {
doesnt actually add any real security for session id stealing as its easy to fake a cookie

2018-10-04 16:33 UTC, mporam commented on edit/security_functions.php
> +        return 'User not in database. Please try again';
by telling the user if they have a incorrect user or password you are opening up yourself to a brute force attack, people can just keep trying usernames until the error doesnt appear. should show a generic error that says incorrect username or password. poorer UX but better security

2018-10-06 09:37 UTC, hoptond commented
project week over, closing this PR for the moment

2018-10-06 09:37 UTC, closed without merging